name: Test CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Tests
        working-directory: src
        run: |
          python -m pytest

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout dépot
        uses: actions/checkout@v3

      - name: Déployer en local
        run: |
          cd $GITHUB_WORKSPACE
          echo "Test déploiement en cours"
          
          docker compose down || true
          docker compose up -d --build
